services:
  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgres/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  pgdata: