// <auto-generated />
using System;
using Booking_System.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking_System.Migrations
{
    [DbContext(typeof(DbApplicationContext))]
    partial class DbApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking_System.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Date = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3211),
                            EmployeeId = 1,
                            End = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3221),
                            Start = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3220)
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Date = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3233),
                            EmployeeId = 2,
                            End = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3235),
                            Start = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3234)
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            Date = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3237),
                            EmployeeId = 1,
                            End = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3238),
                            Start = new DateTime(2022, 10, 15, 11, 38, 26, 877, DateTimeKind.Utc).AddTicks(3237)
                        });
                });

            modelBuilder.Entity("Booking_System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Sebastian",
                            LastName = "Hansen",
                            PhoneNumber = "42424242"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Phil",
                            LastName = "Andersen",
                            PhoneNumber = "84848484"
                        });
                });

            modelBuilder.Entity("Booking_System.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employess");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "isenborg@gmail.com",
                            Name = "Dr. Isenborg",
                            PhoneNumber = "31313131"
                        },
                        new
                        {
                            Id = 2,
                            Email = "wegner@gmail.com",
                            Name = "Dr. Wegner",
                            PhoneNumber = "75757575"
                        });
                });

            modelBuilder.Entity("Booking_System.Models.SmsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmsMessages");
                });

            modelBuilder.Entity("Booking_System.Models.Booking", b =>
                {
                    b.HasOne("Booking_System.Models.Customer", null)
                        .WithMany("Booking")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking_System.Models.Employee", null)
                        .WithMany("Booking")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking_System.Models.Customer", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Booking_System.Models.Employee", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
